### ISSUE TITLE
How to use "UTF-8"

### ISSUE THREAD

**Issue by Messiefee** [Chiel92/unicurses#1]
![untitled](https://cloud.githubusercontent.com/assets/4452863/25257314/db897d94-25fc-11e7-8b11-3965b4d86614.png)
This my error someone can help me?? tnx

**Comment by Chiel92** [comment]
I can't tell from here. The value to be returned by `wgetstr` is supposed to be encoded in utf-8. Then, to return a python string, unicurses tries to decode it. But apparently for you the string isn't a valid utf-8 string.

I'm closing this issue as it is not clear (yet) if this is a bug in unicurses. By all means, continue commenting.

**Comment by Messiefee** [comment]
Ok, I fix the poblem just add the library to the correct one. I downloaded these libraries and extracted them in   \Programs\Python\Python36-32   https://svwh.dl.sourceforge.net/project/pdcurses/pdcurses/3.4/pdc34dllu.zip
