### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by MMd95** [Chiel92/unicurses#7]
is there any docs to learn unicurses? i could find none

**Comment by Chiel92** [comment]
There is none. You can use ncurses guides to get an idea of how it works.

**Comment by MMd95** [comment]
i tried but i couldnt find good examples like how to scroll?!

**Comment by hotlittlewhitedog** [comment]
Use the doc of ncurses. 
To scroll you need to create a "pad" (buffer) and take a block of this buffer if you go down, up, left, right.
